import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, Check, ChevronRight, Heart, Home, MapPin, MessageCircle, Search, Sparkles, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { artists, type Artist, packages } from "@/api/mock";

export function AppHeader() {
  return <header className="border-b border-white/10 bg-wine/95 px-5 py-5 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link to="/" className="font-serif text-2xl italic tracking-tight text-ivory">Glowtique</Link><nav className="hidden items-center gap-8 text-[10px] uppercase tracking-[0.2em] text-ivory/60 md:flex"><Link to="/browse" className="transition hover:text-blush">Discover artists</Link><a href="#how-it-works" className="transition hover:text-blush">How it works</a><a href="#become-an-artist" className="transition hover:text-blush">For artists</a></nav><div className="flex items-center gap-3"><Button asChild variant="ghost" size="sm" className="hidden text-ivory/70 hover:bg-white/10 hover:text-ivory sm:inline-flex"><Link to="/customer">Sign in</Link></Button><Button asChild size="sm" className="rounded-xl bg-gold text-wine hover:bg-gold/90"><Link to="/browse">Book now</Link></Button></div></div></header>;
}

export function MobileTabs({ active = "home" }: { active?: string }) {
  const items = [{ key: "home", label: "Home", icon: Home, to: "/" }, { key: "search", label: "Search", icon: Search, to: "/browse" }, { key: "bookings", label: "Bookings", icon: CalendarDays, to: "/customer" }, { key: "profile", label: "Profile", icon: UserRound, to: "/customer" }];
  return <nav className="fixed inset-x-0 bottom-0 z-30 mx-auto flex max-w-md items-center justify-around border-t border-wine/10 bg-cream px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-3 text-wine shadow-[0_-12px_30px_-22px_var(--wine)] md:hidden">{items.map(({ key, label, icon: Icon, to }) => <Link key={key} to={to} className={`flex min-w-16 flex-col items-center gap-1 text-[10px] ${active === key ? "text-wine" : "text-wine/45"}`}><Icon className="size-5"/><span>{label}</span></Link>)}</nav>;
}

export function Stars({ rating }: { rating: number }) { return <span className="inline-flex items-center gap-1 text-xs text-gold"><span>★★★★★</span><span className="text-ivory/60">{rating.toFixed(1)}</span></span>; }

export function ArtistCard({ artist, compact = false }: { artist: Artist; compact?: boolean }) {
  return <Link to="/artists/$id" params={{ id: artist.id }} className={`group block shrink-0 rounded-2xl bg-wine-700 p-3 ring-1 ring-white/10 transition duration-300 hover:-translate-y-1 hover:ring-blush/60 ${compact ? "w-44" : "w-full"}`}><div className={`relative overflow-hidden rounded-xl ${compact ? "aspect-square rounded-full" : "aspect-[4/5]"}`}><img src={artist.image} alt={`${artist.name}, makeup artist`} loading="lazy" width={640} height={720} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/><span className="absolute left-2 top-2 inline-flex items-center gap-1 rounded-full bg-wine/85 px-2 py-1 text-[9px] uppercase tracking-widest text-gold"><Check className="size-3"/> Verified</span></div><div className="mt-3"><div className="flex items-center justify-between gap-2"><h3 className="truncate font-serif text-lg text-ivory">{artist.name}</h3><Stars rating={artist.rating}/></div><p className="mt-1 truncate text-[11px] font-mono text-ivory/50">{artist.specialties.slice(0, 2).join(" · ")} · from ₹{artist.startingPrice.toLocaleString("en-IN")}</p></div></Link>;
}

export function SearchPanel() {
  return <div className="rounded-2xl bg-wine-700 p-3 ring-1 ring-white/10"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><div className="flex items-center gap-2 rounded-xl bg-cream px-3 py-3 text-wine"><MapPin className="size-4 shrink-0 text-wine/50"/><span className="truncate text-sm font-medium">Mumbai</span></div><div className="flex items-center gap-2 rounded-xl bg-cream px-3 py-3 text-wine"><Sparkles className="size-4 shrink-0 text-wine/50"/><span className="truncate text-sm font-medium">Bridal makeup</span></div><div className="flex items-center gap-2 rounded-xl bg-cream px-3 py-3 text-wine"><CalendarDays className="size-4 shrink-0 text-wine/50"/><span className="truncate text-sm font-medium">This Saturday</span></div><Button asChild className="h-12 rounded-xl bg-gold px-6 text-wine hover:bg-gold/90"><Link to="/browse"><Search className="size-4"/>Find artists</Link></Button></div></div>;
}

export function PackageCard({ packageItem = packages[0], selected = false, onSelect }: { packageItem?: typeof packages[number]; selected?: boolean; onSelect?: () => void }) {
  return <button type="button" onClick={onSelect} className={`w-full rounded-2xl p-4 text-left transition ${selected ? "bg-cream text-ink ring-2 ring-gold" : "bg-white/5 text-ivory ring-1 ring-white/10 hover:bg-white/10"}`}><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-serif text-xl">{packageItem.name}</p><p className={`mt-1 truncate text-xs ${selected ? "text-ink/60" : "text-ivory/55"}`}>{packageItem.duration} · {packageItem.detail}</p></div><span className="shrink-0 font-serif text-xl">₹{packageItem.price.toLocaleString("en-IN")}</span></div></button>;
}

export function SectionHeading({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[0.2em] text-blush">{eyebrow}</p><h2 className="mt-2 font-serif text-3xl leading-none text-ivory">{title}</h2></div>{action}</div>; }

export function DashboardShell({ role, title, children }: { role: "customer" | "artist" | "admin"; title: string; children: React.ReactNode }) {
  const links = role === "customer" ? [["Overview", "/customer"], ["My bookings", "/customer"], ["Payments", "/customer"], ["My reviews", "/customer"]] : role === "artist" ? [["Overview", "/artist-dashboard"], ["Bookings", "/artist-dashboard"], ["Portfolio", "/artist-dashboard"], ["Earnings", "/artist-dashboard"]] : [["Overview", "/admin"], ["Verification queue", "/admin"], ["Users", "/admin"], ["Payments", "/admin"]];
  return <div className="min-h-screen bg-cream text-ink"><div className="mx-auto grid min-h-screen max-w-[1500px] lg:grid-cols-[240px_1fr]"><aside className="hidden border-r border-wine/10 bg-wine p-6 text-ivory lg:block"><Link to="/" className="font-serif text-2xl italic">Glowtique</Link><p className="mt-12 font-mono text-[10px] tracking-[0.18em] text-blush">{role.toUpperCase()} STUDIO</p><nav className="mt-5 space-y-1">{links.map(([label, to]) => <Link key={label} to={to} className="block rounded-xl px-3 py-3 text-sm text-ivory/65 transition hover:bg-white/10 hover:text-ivory">{label}</Link>)}</nav></aside><main className="min-w-0"><div className="border-b border-wine/10 bg-cream px-5 py-5 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[0.18em] text-wine/50">GLOWTIQUE / {role}</p><h1 className="mt-1 font-serif text-3xl text-wine">{title}</h1></div><Button asChild variant="outline" className="rounded-xl border-wine/20 text-wine hover:bg-wine/5"><Link to="/">View marketplace</Link></Button></div></div><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8">{children}</div></main></div></div>;
}

export { ArrowRight, ChevronRight, Heart, MessageCircle, artists, packages };